---
platform: linux

image_resource:
  type: docker-image
  source: {repository: sghakinternet/ci}

inputs:
  - name: ci-tasks
  - name: result

outputs:

params:

run:
  path: ci-tasks/tasks/evaluate-result/task.sh
